---
title: Template
author: Lorenz M. Pammer, MD
date: last-modified
editor: source
documentclass: article
page-layout: full
format:
  eisvogel-pdf:
    default:
      fig-align: center
      papersize: a4
      classoption: landscape
      geometry:
        - top=30mm
        - bottom=30mm
        - heightrounded
      mainfont: Source Sans Pro
      sansfont: Source Sans Pro
  html:
    figure-width: 100%
    fig-align: center
    default-image-extension: svg
execute:
  echo: false
  warning: false
  #bibliography:
---


```{r}
library(here)
library(gtsummary)
library(tidyverse)
#load(.)
```

# Tables

## Table 1
```{r}
#| label: tbl-baseline
#| fig-cap: "Table 1 - baseline statistics"
iris %>%
  tbl_summary(by = Species)
```


See @tbl-baseline for baseline statistics.


# Figures
## Figure 1
@fig-num1 shows the diferences between groups.
```{r }
#| label: fig-num1
#| fig-cap: "Figure 1 - ... "
ggplot(iris) + aes(group=Species,x=Sepal.Length,y=Sepal.Width)+
  geom_point()
# figure code
``` 
